### ISSUE TITLE
Game freezes for about 4 seconds when a fight starts or a round is finished.

### ISSUE THREAD

**Issue by Borkason** [ja2-stracciatella/ja2-stracciatella#1219]
### What is wrong

Game freezes for about 4 seconds when a fight starts or a round is finished. Happens every time.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release |  GOG setup_jagged_alliance_2_1.12_(17794).exe   | I don't know what you mean by that |    first time I play this  |

- Windows 10

**Comment by ja2-derek** [comment]
Confirmed.  Thank you for the report. We will see what we can do about it.

The root problem is that saves are noticeably slow on Windows. DiD mode saves the game on every round in turn-based so it is affecting the gameplay quite badly.

**Comment by ja2-derek** [comment]
The slowness is caused by Windows' built-in virus scan. One way to work-around the problem is to exclude our process from the Windows virus scan. 

In Windows Security > Virus & threat protection > Virus & threat protection settings > Manage settings > Exclusions > Add or remove exclusions > Add an exclusion > Process > Enter process name: "ja2.exe"
