### ISSUE TITLE
Crash when handing Fatima the letter while another merc discovers an item

### ISSUE THREAD

**Issue by FluffyQuack** [ja2-stracciatella/ja2-stracciatella#1378]
I was watching a streamer and he got this crashing bug handing Fatima the quest letter while another merc discovered an item: https://clips.twitch.tv/PowerfulRenownedKoalaAllenHuhu--4e0bLZ5VWYwZrlw

I haven't looked into this personally, so I don't know if it's 100% reproducible.

I believe he was using v0.18.0 of Straciatella. I don't know if this is a vanilla bug or not.

There's another reported issue related to mercs finding items. Maybe it's related: https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1367

**Comment by ja2-derek** [comment]
The video shows 0.17.0 when he restarted the game. But likely still an issue in 0.18.

**Comment by ja2-derek** [comment]
It is reproducible. When there are pending dialogues, the give-item action is put into a pending queue and there is a global variable `g_pending_approach_object`. 

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/e23678b74af7e7fa2ccaf067eb44993184af0a33/src/game/Tactical/Interface_Dialogue.cc#L210-L217

But the same object gets deleted before it is processed by the NPC logic. 

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/e23678b74af7e7fa2ccaf067eb44993184af0a33/src/game/Tactical/Handle_Items.cc#L2353-L2355

Call stack when error happens:

```
 >	ja2.exe!NPCConsiderReceivingItemFromMerc(const unsigned char ubNPC, const unsigned char ubMerc, const OBJECTTYPE * const o, NPCQuoteInfo * const pNPCQuoteInfoArray, NPCQuoteInfo * * const ppResultQuoteInfo, unsigned char * const pubQuoteNum) Line 750	C++
 	ja2.exe!ConverseFull(unsigned char ubNPC, unsigned char ubMerc, Approach bApproach, unsigned char approach_record, OBJECTTYPE * o) Line 1614	C++
 	ja2.exe!InternalInitiateConversation(SOLDIERTYPE * pDestSoldier, SOLDIERTYPE * pSrcSoldier, Approach bApproach, unsigned char approach_record, OBJECTTYPE * approach_object) Line 313	C++
 	ja2.exe!HandlePendingInitConv() Line 250	C++
	ja2.exe!HandleDialogue() Line 287	C++
 	ja2.exe!MainGameScreenHandle() Line 581	C++
 	ja2.exe!GameLoop() Line 205	C++
 	ja2.exe!MainLoop(int msPerGameCycle) Line 262	C++
 	ja2.exe!SDL_main(int argc, char * * argv) Line 532	C++
 	ja2.exe!main_getcmdline(...) Line 161	C
```

Because the object is a deleted pointer, `item_to_consider` is now a garbage value, we have a NULL object instead of an `ItemModel` :

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/c75a2773eb1905c82111b9bb294ca7ecf5fb5bb0/src/game/TacticalAI/NPC.cc#L750
