### ISSUE TITLE
Unable to use "repair" in P3 underground sector

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#152]
Originally reported by: **Andrey Tuzov (Bitbucket: [Kokkolar](http://bitbucket.org/Kokkolar), GitHub: [Kokkolar](http://github.com/Kokkolar))**

----------------------------------------

Btw "doctor" works well.

http://www.youtube.com/watch?v=mPIOH1aaCj4

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/152

**Comment by derSteFfi** [comment]
still present. when i get the squad back to the daylight, maddog can use repair (btw: the youtube link is still up :) )

**Comment by derSteFfi** [comment]
here's the reason: (Build/Strategic/Assignments.cc:5161)
```C
if( pSoldier -> bSectorZ ==0 )
{
	fShowRepairMenu = TRUE;
	DisplayRepairMenu(*pSoldier);
}
```
The merc can repair, but the menu to choose what to repair isn't displayed. This check makes no sense imho, since reparing underground is fine and the rest of the code also assumes that. PR in progress.

**Comment by JAsmine-ja2** [comment]
If I remember correctly, it was impossible in Vanilla JA2 to do _any _ task (like training etc) while your merc is underground.
If we repairing underground is allowed, then all tasks should be allowed, shouldn't they?
But can't this lead to problems? What happens if the sector above gets attacked or taken by the army while we are underground?
Could this lead to enabling the training of militia underground? It probably shouldn't, since it would severly affect the game when playing in Sci-Fi.

**Comment by derSteFfi** [comment]
training (not militia) is still not allowed, a comment somewhere in the code said that it's not supported. I tried it, worked fine.
Militia, Trainer, Student and Practise are handled differently and can be made available underground seperatly. This, for now, was a bug fix, because the Code (in comments) stated that repairing should be possible underground but didn't show the menu.
I think practicing and teaching/learning are possible underground, Militia on the other side makes no sense. This also shouldn't interfere with attacks on the surface since the underground sector is seperated from that (e.g. You have Militia in Mine sectors but Aliens can have sectors below this captured)
I'll open a proposal to enable training (or parts of it) underground to split it out of this bug.

**Comment by selaux** [comment]
As stated in #239 I would hide this behind a switch, because it is not vanilla behavior, right?

**Comment by derSteFfi** [comment]
for the rest, i think this is OK, but for this, repairing was clearly thought to be allowed underground: (Assignments.cc, line 519)
```C
static BOOLEAN BasicCanCharacterRepair(const SOLDIERTYPE* const s)
{
	return
		s->bMechanical > 0 &&
		AreAssignmentConditionsMet(*s, AC_UNDERGROUND);
}
```
The AC_UNDERGROUND states that it doesn't matter if you're underground, you're allowed to repair. Only the box for selecting what to repair didn't appear, because when drawing it, a check whether you're underground comes in. I'd consider this a bug, not a decision.
