### ISSUE TITLE
Proposal: convert class Soldier to a namespace

### ISSUE THREAD

**Issue by momoko-h** [ja2-stracciatella/ja2-stracciatella#1558]
class Soldier was obviously created to bundle some of the gigantic number of functions operating on struct `SOLDIERTYPE` under a common name. However, since its inception in 2013 this class hasn't gained much traction which isn't surprising when you consider that most of the code base uses `SOLDIERTYPE`* and you have to create a wrapper Soldier object first to access the class methods. A nice example is function `ExecuteOverhead` in Overhead.cc where the Soldier pointer is used five times while the corresponding `SOLDIERTYPE` pointer is used 197 times.

Nevertheless the idea of having a container for soldier related functions is certainly sound, not the least because it would help IntelliSense locate functions, I just believe that the class approach was wrong. Since class declarations cannot be split across multiple files all declarations would have to be in Soldier.h, which would be crazy.

A namespace Soldier OTOH could be amended everywhere, anytime somebody works on a `SOLDIERTYPE` related function and is in the mood to change the name of a function like `DeleteSoldier` to `Soldier::Delete`, for example.

Converting just class Soldier to a namespace is not much work but before I start I'd first like to hear the opinion of the maintainers. Do you see this proposal as an improvement or is it not worth the hassle?

**Comment by lynxlynxlynx** [comment]
I only have a slight preference for the class approach, but it depends on the motivation of others (since I doubt I would work on this). It's clear the gradual port to c++ along ja2s development has been shallow, less clear if there's enough interest to go for proper encapsulation. A dream where we wouldn't need both Soldier and SOLDIERTYPE, because they'd be merged and full of smaller classes of smaller classes, neatly organized and self-contained.

**Comment by momoko-h** [comment]
I'll close this issue based on the lack of interest in the idea.
