### ISSUE TITLE
Skyrider crashes the game on my current progress

### ISSUE THREAD

**Issue by Trokinos** [ja2-stracciatella/ja2-stracciatella#1559]
Using Stracciatella 0.19.1 on window 10

On my current game, i ran into a crash that can be reproduced everytime : 

Here is the save : 
[2022-05-29t12-12-34z-helo-crash.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/8793336/2022-05-29t12-12-34z-helo-crash.zip)

Squad 1 is already in the helicopter.
Double Click on C6 to send Skyrider to that part of San Mona 

![err1](https://user-images.githubusercontent.com/14024168/170868043-a08da960-7d05-47df-b7f3-06fe925bfed7.jpg)

Press time acceleration -> it will always crash (at least it does for me) to desktop

Can't manage to capture the error message in the log window unfortunately as it is closing at the same time as the game crash (and close), i spotted something about "soundloaddisk" in the short interval before the log window closes itself

**Comment by momoko-h** [comment]
This only crashes for me right after a fresh restart of the game when I immediately load the provided save. The destination of the helicopter doesn't matter.

The reason is that `HandleNewSectorAmbience` hasn't been called yet, so `gAmbData` is empty. Usually `LoadSavedGame` takes care of that, but for this save the fWorldLoaded flag is false and we end up in a branch where the call to `HandleNewSectorAmbience` does not happen.
