### ISSUE TITLE
Accelerated bleeding when returning to realtime

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#160]
Originally reported by: **L C (Bitbucket: [LCJr](http://bitbucket.org/LCJr), GitHub: [LCJr](http://github.com/LCJr))**

---

Rarely when switching back from turnbased to realtime mercs will bleed at accelerated rate losing several (6+?)  health points per second.   Affects player mercs, friendly militia and possibly enemies.

For example I had one merc take a 10 pt. wound and on returning to realtime he bled at the rate of -1 pts for an additional 21 pts. in ~3  seconds realtime.  Doesn't occur too often, so far in my current game only twice in 22 battles.   Exiting to the strategic map and then returning to the tactical/sector map fixes the problem.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/160

**Comment by JAsmine-ja2** [comment]
Just experienced this bug in v0.15.1
It is really dangerous and possibly game breaking.
The only thing one can do is quickly enter strategic view to stop real-time.
The bleeding goes back to normal when re-entering tactical.
I will try to make a new savegame of this next time...

**Comment by lynxlynxlynx** [comment]
I bet previous time compression somehow kicks in.

**Comment by JAsmine-ja2** [comment]
Yeah. When you artificially compress time with a merc being wounded, it looks exactly the same.

**Comment by geca** [comment]
> The only thing one can do is quickly enter strategic view to stop real-time.
> The bleeding goes back to normal when re-entering tactical.

Which was the exact workaround for missing money description box (#379). What I found out debugging that issue was that game compression mode is set to `TIME_COMPRESS_X1 `after loading the game. This ensures `( uiTime - guiLastTacticalRealTime ) > uiCheckTime` is met which in turn executes `HandleTacticalEndTurn ` function that (probably) also causes rapid bleeding.

When entering strategic screen, compression mode is set to `TIME_COMPRESS_60MINS`, and therefore later skipping `HandleTacticalEndTurn` in tactical screen.
