### ISSUE TITLE
Segfault on killing any next enemy, even if you leave and re-enter sector

### ISSUE THREAD

**Issue by wertyzp** [ja2-stracciatella/ja2-stracciatella#1664]
### What is wrong
Details, details, details.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.20.0 commit fa3273c6bcbcbcdf6f73becc3cf8718253d40ac9 | head  |    yes    |    yes     |
Savegame:

https://easyupload.io/xourr9

Kill any next enemy, results in segfault
No backtrace generated

![Screenshot from 2022-10-08 16-35-11](https://user-images.githubusercontent.com/5189304/194710249-439c54de-8042-49df-989c-16a1b318ae40.png)

**Comment by momoko-h** [comment]
You managed to exceed the game's limit of 100 corpses, that's not a problem that can be fixed by reloading. Somewhat amusing: the 1.13 team dealt with this issue 14 years ago when they first increased `MAX_ROTTING_CORPSES` to 250, then to 500.

Possible solutions:

1. Ignore corpses after the 100th. Seems bad because it probably just pushes the problem further up. I don't trust `HandleSoldierDeath()` to handle this gracefully.
2. Just increase `MAX_ROTTING_CORPSES`. This would mean that saves with more than 100 corpses can no longer be loaded with older versions and doesn't prevent the some crazy person from crashing the game when the new limit is reached.
3. Change the fixed size array to a vector. Breaks compatibility with older versions again for >100 corpses, but players can now fill every grid with a corpse if they wish.

**Comment by momoko-h** [comment]
So a closer examination revealed that simply increasing MAX_ROTTING_CORPSES is probably unsafe. [Structure.h](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/4e06cac7ddfb76283f0ead3aeaa9cb27984a155d/src/game/TileEngine/Structure.h#L28) has this beauty:

```
// ATE: Increased to allow corpses to not collide with soldiers
// 100 == MAX_CORPSES
#define INVALID_STRUCTURE_ID			( TOTAL_SOLDIERS + 100 )
#define IGNORE_PEOPLE_STRUCTURE_ID		(TOTAL_SOLDIERS+101)
```

and in [Structure.cc](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/4e06cac7ddfb76283f0ead3aeaa9cb27984a155d/src/game/TileEngine/Structure.cc#L62)

`#define FIRST_AVAILABLE_STRUCTURE_ID (INVALID_STRUCTURE_ID + 2)`

[and](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/4e06cac7ddfb76283f0ead3aeaa9cb27984a155d/src/game/TileEngine/Structure.cc#L776)

```
	else if (pLevelNode->uiFlags & LEVELNODE_ROTTINGCORPSE)
	{
		// ATE: Offset IDs so they don't collide with soldiers
		usStructureID = (UINT16)(TOTAL_SOLDIERS + pLevelNode->pAniTile->v.user.uiData);
	}

```
`v.user.uiData` is the result of `CORPSE2ID`. 

This means the 101st corpse would have INVALID_STRUCTURE_ID, the 102nd would have IGNORE_PEOPLE_STRUCTURE_ID and the the following corpses would collide with the IDs following FIRST_AVAILABLE_STRUCTURE_ID. Since INVALID_STRUCTURE_ID is used all over the place it's hard to predict what kind of problems increasing its value might create. 

So it looks like Option 1, not creating any more corpses after the 100th, is probably the least bad option after all.

**Comment by wertyzp** [comment]
@ja2-derek thanks for your response! 
There's another bug, I think also same issue as you described. At cambria hospital, I kill last enemy and suddenly his corpse converted to the ... child! And civilians attacked me

**Comment by ja2-derek** [comment]
That was @momoko-h :stuck_out_tongue: 

I agree with what @momoko-h mentioned. I would consider 100+ corpses an edge case, and would rather gracefully handle (or ignore) the corpses after the 100th without tempering with save and data structures.

**Comment by momoko-h** [comment]
I tested this a bit more: saving and loading works fine after increasing the max. number. Older builds with the current limit of 100 can load such saves, they're just in a very fragile situation where the next new corpse crashes the game.

I also looked at those structure IDs more closely: the only function that generates them is `AddStructureToWorld`. They are not used in data files and are not saved, so changing `INVALID_STRUCTURE_ID` should be safe. The only drawback is that this reduces the number of other structures in the map. The current limit is 65536 - 258 = 65278, so increasing the number of corpses to 400 would reduce that limit to 64978, that is still more than two structures per grid.
