### ISSUE TITLE
CAWS some burst fire weapon sounds are missing/not playing.

### ISSUE THREAD

**Issue by ja2forever** [ja2-stracciatella/ja2-stracciatella#1764]
JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  ja2-stracciatella_0.20.0-git+439a6d3_win-msvc64  | JA2 Gold 1.12 English CD  |    no    |    dunno     |

CAWS have missing buckshot(blue mag) and slug(red mag) ammo burst fire sounds - checked on default 3-shot bursts, no mods:
-BS 3 or more shots left burst - missing
-BS 2 shots left burst - missing
-BS 1 shot left burst - missing
-SLG 3 or more shots left burst - OK
-SLG 2 shots left burst - OK
-SLG 1 shot left burst - missing

Screenshot with errors:

![JA2_CAWS_SOUND](https://user-images.githubusercontent.com/122088263/213758337-3573d50c-31a2-407d-b6a9-ddd2dd4d5204.png)

**Comment by arnodick** [comment]
I've noticed this as well, and it seems like the value for how many shots are fired in the burst is randomized when trying to find the correct wav. (burst 9.wav, burst 27.wav etc.) Could it be retrieving a datetime value instead of the shot count?
Also, even in vanilla JA2 I believe there wasn't actually any sound file for the caws burst, and so it defaulted to bursttype1.wav, which I believe doesn't happen in stracciatella any more. Instead there is no default wav and stracciatella just doesn't play sound.

**Comment by momoko-h** [comment]
No, this isn't random. If you look closely you'll notice that these numbers are multiples of 9, that's because the game treats one unit of buckshot ammunition as 9 separate bullets, with 1⁄4 damage per bullet. The problem might be solvable just like #1730: find the CAWS entry in `weapons.json` and add a `burstSound` entry (I didn't test this hypothesis).

**Comment by selaux** [comment]
I think with this new information even the fix for #1730 might be flawed, because the correct sound to play also depends on the number of bullets remaining in the gun. So even the RPK now probably always plays the "full" burst in all cases, even when only a single bullet remains in the gun.

**Comment by arnodick** [comment]
Interesting. For me it kind of stick to multiples of 9, but I've gotten other values sometimes.

The CAWS has shotgun burst %d.wav as its burstSound. Every .wav file except shotgunburst1.wav is in the sounds.slf file.

![ja2-launcher exe 1_29_2023 8_23_24 PM](https://user-images.githubusercontent.com/10444394/215364899-354f586f-9656-42bb-8f17-6d3a68018a5c.png)

**Comment by arnodick** [comment]
Interesting. For me it kind of stick to multiples of 9, but I've gotten other values sometimes.

The CAWS has shotgun burst %d.wav as its burstSound. Every .wav file except shotgunburst1.wav is in the sounds.slf file.

![ja2-launcher exe 1_29_2023 8_23_24 PM](https://user-images.githubusercontent.com/10444394/215364899-354f586f-9656-42bb-8f17-6d3a68018a5c.png)

**Comment by momoko-h** [comment]
For this to happen, soldier->bBulletsLeft must be 15, 23 or 25. AFAICT that's possible if FireWeapon gets called in the middle of an animation, maybe the gun jammed and unjammed during the burst? Was the status of the CAWS less than 80%?

One possible approach would be to add some code in [UseGun](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/7574409fcfdf483fd02a6328da17b166a9daae72/src/game/Tactical/Weapons.cc#L738) to check if the computed sound exists, and use some fallback sound if it doesn't.

**Comment by arnodick** [comment]
CAWS was 100% status, minus whatever the burst lowered its status by. It did have a barrel extender on it so I tested it without the extender and still got some results not divisible by 9. I used GABBI cheats to get some more CAWS ammo, but not sure how that would affect things.

After thinking about I'm pretty sure this bug was exactly the same in vanilla. CAWS slug burst sounds worked fine except for a single shot burst, which makes sense since there is no shotgunburst1.wav in sounds.slf, and buckshot bursts always defaulted to bursttype1.wav, presumably due to this 9 bullets per shot issue.

![ja2-launcher exe 1_31_2023 10_47_47 AM](https://user-images.githubusercontent.com/10444394/215793292-1d4034fe-a9bf-4ef0-9e9a-1435e390d0ca.png)

**Comment by Danf96** [comment]
Is there currently anything already in place to handle weapons with different gun sounds based on ammo type? In vanilla the CAWS buckshot burst is different from slugs.
https://youtu.be/ibhCACwWE4k?si=XcEhJFb87jwcs3S1&t=795

**Comment by momoko-h** [comment]
No, the sounds are part of the WeaponModel class. You would have to move them to the AmmoTypeModel to implement that.

**Comment by selaux** [comment]
The first one is `sounds/weapons/shotgun burst 3.wav` the other one is the fallback sound `sounds/weapons/bursttype1.wav`.
