### ISSUE TITLE
Increas the displayed character limit, so that the full lines in AIM and MERC Bios is useable.

### ISSUE THREAD

**Issue by Moddi** [ja2-stracciatella/ja2-stracciatella#1986]
Recently I rewrote Scope's AIM bio. I wanted to exchange the upper and the lower part of her text, so that the apology about the mistake does not take up her actual new bio. While doing so I realized, that the character limit of the actual displayed text in both parts, the actual bio and the additional info, is smaller then what text could actually be displayed on the screen in a single line. E.g. the additional info has two lines of space available, but the actually displayed character limit is roughly only 1.5 lines. Same is true for the main bio. Here, also the text stops being displayed, despite there being half a line or even more empty.

There is probably an integer number somewhere using "normal" bit numbers (32, 64, 108, etc.) and not using the number of the character limit of the actual line.

**Comment by momoko-h** [comment]
The actual limits are 400 characters for the main description and 160 characters for the additional information., hardly enough to fill the available display area.

The root of the problem are simply the awful .edt files. EDT can hardly even be called a file format, it is just a blob of obfuscated UCS-2 code points (which are often even incorrectly encoded and have to be fixed up) and it is up to the user of the files to make some sense out of that blob. Since EDT has absolutely no metadata you cannot simply decree that some strings should be longer or shorter than others.

Ideally we would have some mechanism in place that would allow users to override all .edt files with JSON files, not just mercbios.edt and aimbios.edt. That would not only solve this problem; users wouldn't have to use specialized Windows-only tools to edit these files.

**Comment by selaux** [comment]
Yep. I think there is already an approach that does that for some dialogue files. Not sure if it simply first searches for `.json` and then falls back to `.edt`.

**Comment by ja2-derek** [comment]
We have this "test-json-dialog" mod: https://github.com/ja2-stracciatella/ja2-stracciatella/tree/master/assets/mods/test-json-dialogs/
