### ISSUE TITLE
crash with error -1073741819 in A10 map of Return to San Amaro mod. If char no.71 is deleted from map it loads ok

### ISSUE THREAD

**Issue by az75199** [ja2-stracciatella/ja2-stracciatella#2077]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git | eg. JA2 Gold Dutch  |    yes/no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

worked fine in 0.21
https://www.mediafire.com/file/e3bpas86qmnytak/az75mods.zip/file

**Comment by Srandista** [comment]
I did some quick tests and the breaking point is in this build: https://storage.googleapis.com/ja2-builds/index.html#nightlies/ja2-stracciatella_0.22.0-20240728+98ed56d/

The build from the day before works fine.

**Comment by ShishkinP** [comment]
Already on it. Seems like the reason is the absence of script records for RPC71 and null pointer as a result.

**Comment by lynxlynxlynx** [comment]
Great work everyone. :)

**Comment by ShishkinP** [comment]
@az75199 You probably experienced this on the build that is after the script records externalization update and before the profiles one. Because the latest build wouldn't crash since most chars are not even spawned. Prof.dat is no longer supported so to spawn, for example, the 71th char on your map you'll have to add `"sector": "A10"` in merc-profiles.json for `"profileID": 71`

The profiles externalization update is not finished yet. Field names, their values or maybe even the number of profile-related json files will change. So, postpone the dat-to-json transfer for when the update is done to avoid double work.
