### ISSUE TITLE
Game crashes after the turn

### ISSUE THREAD

**Issue by Srandista** [ja2-stracciatella/ja2-stracciatella#2124]
### What is wrong
I was attacking Meduna residential sector, when my game crashes. It did on both occasions, where it autosaves. I don't see any logs, but last two entries in the status window are as follows:

[WARN] game\Tactical\Soldier_Control.cc: SetSoldierGridNo: ID 25 (SOLDIER) has no structure
[WARN] game\Tactical\Soldier_Control.cc: SetSoldierGridNo: ID 38 (SOLDIER) has no structure

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  latest nightly | JA2 1.06 EN  |   ?    |    ?     |

I attach affected saves. Game is running under Windows 10.

[Meduna-saves.zip](https://github.com/user-attachments/files/17837125/Meduna-saves.zip)

**Comment by momoko-h** [comment]
This crashes due to a null pointer dereference in `StartInterrupt()`. The interrupt list is somehow messed up which isn't that surprising when you look at the weird way it got implemented.

Those two warnings are totally unrelated. I added them a while ago in the hope they'd help me find the cause for soldiers becoming unhittable. Since they failed to do that and #2116 may have solved that problem I'll remove them first.

**Comment by momoko-h** [comment]
So AFAICT what's happening here is this:

1. After ending the turn the enemies have their turn but nothing happens so we drop out of turn based combat.
2. Moments later Martin and a soldier spot each other so we go back to turn based but have to resolve an interrupt.
3. During the interrupt the game tries to build the AI list for the enemy team but the only soldier left is out of breath so he doesn't get added to the list.
4. StartInterrupt() then crashes because it doesn't expect `BuildAIListForTeam` to return an empty list and just tries to use the first entry.
