### ISSUE TITLE
Create a tiny website for our landing page

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#244]
Just so users can find information more easily. Relevant content can be migrated from the wiki. A github subdomain can be set up and then used everywhere instead of the github repo link.

**Comment by selaux** [comment]
So what do you think? http://ja2-stracciatella.github.io

Looks kind of generic, but that can be improved in the future, e.g. by a cool logo.

**Comment by derSteFfi** [comment]
looks great. much fancier than it sounded yesterday :)
also looks good on mobile devices, btw. definite +1

**Comment by lynxlynxlynx** [comment]
Wow, nice! I think we should add all the menu links to the bottom of the first page too (or before the features), so it's clearer where to get it and how to run it.

**Comment by selaux** [comment]
Added the menu links (not the development one, since it's probably not for getting users set up). Will close this then.

**Comment by selaux** [comment]
I just forgot: Where do the links need to be updated? Can anyone do this? Lets keep this open as a reminder that it still needs to be done.

**Comment by lynxlynxlynx** [comment]
Moddb, bp stickies, README come to mind. Not sure what to do about the wiki.

I'd move at least news out of the readme. For downloaders there's changes.md and this way updating will be easier and the actual news more trackable.

**Comment by JAsmine-ja2** [comment]
moddb profile updated. News article there will go live in a day or so.

Suggestion for homepage:

- Maybe add link to changelog to download area?
- Maybe add link to wiki?
- Maybe add features as an extra menu besides "download", "development"?

The homepage looks really nice! Good job! :+1:

**Comment by selaux** [comment]
- I thought about adding the changelog, but for the current release there is none, so it will bring no value. We can add it with the next release.
- The wiki contains mostly stuff for developers and I want to leave the homepage as clean as possible. The only part I would add is the FAQ if requested.
- Without the features the "Home"-Page would look kind of bare, as would the features page. We could move the features to another page if there are some more features to present.

NB: Basically most of the work was done by the developer of [beautiful-jekyll](http://deanattali.com/beautiful-jekyll/) so the kudos go to him :smile:. The page should be relatively easy to maintain, since our content is mostly a bunch of markdown files (see https://github.com/ja2-stracciatella/ja2-stracciatella.github.io).

**Comment by selaux** [comment]
Is this okay as our first news article: https://github.com/ja2-stracciatella/ja2-stracciatella.github.io/blob/51ad97674a62a107e91061ec569d9d2f62a18b1c/_posts/2016-03-12-ja2-stracciatella-continued-continued.md. Then I will publish.

**Comment by JAsmine-ja2** [comment]
Seems okay to me. All important things covered.
Another thing:
Maybe, the homepage could somewhere link to the subforum @Bear's Pit and the moddb profile?

**Comment by selaux** [comment]
Added the old news and links, will close this, updates to the website can now be discussed [here](https://github.com/ja2-stracciatella/ja2-stracciatella.github.io).
