### ISSUE TITLE
Some general stuff in the Stracciatella folder

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#313]
I downloaded v0.15 and here are some small things I noticed (These issues were ofc present before the new version already).

- README.ENG and README.RUS still point to the old BB repo. Should be changed. Maybe include both the development page and the homepage?
- We have two changelogs in the Stracciatella folder: changelog.txt (old changelog) and changes.md (Stracciatella Continued). Maybe merge them into one file? Or make it clear which file is the right one?
- Why are there two .bat files for russian AND russian Gold version? Why is there only one .bat for english version? Confusing...
- Changelog.txt and \externalized\readme.txt are a mess when viewed in standard MS Notepad. Better programs like Notepad++ can view them without problems. Maybe change encoding of the files?

**Comment by derSteFfi** [comment]
for the last point: it's not the encoding, its the line endings (unix and win differ). notepad++ (and some other editors in win, too) can handle unix-style line endings, notepad doesn't. since unix supports both in most situations and programs, it should be easy to switch here. I'll prepare a PR.

third point: I saw the distinction in multiple places, but I don't know why it was made. Does anyone know the reason?

second point: None of them is 'right' :) the current 'changelog' is our git history, both of the files are from different eras. I'll include a merge of them in my PR for the last point.

first point: I'll fix that in the PR.

PR incoming in about an hour...

**Comment by lynxlynxlynx** [comment]
The two Russian versions are just different enough for us to need to pass different parameters to ja2. Nothing fishy there.
