### ISSUE TITLE
Helicopter is ignored by pathfinding

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#317]
When starting a new game, the helicopter is present in Drassen but ignored when finding paths (moving a merc). Moving though it is not possible though. Screenshot will follow...

**Comment by JAsmine-ja2** [comment]
![heli_path](https://cloud.githubusercontent.com/assets/17213795/17392177/dd6bd54c-5a1b-11e6-9e0f-e32e5bea008a.jpg)

This screenshot is from English v1.12 without Stracciatella. The bug is present here, too. The merc stops right in fron of the heli.

While the technical side of this bug is probably severe, the impact on gameplay is not too big, since the heli is parked in a remote place on the map.
