### ISSUE TITLE
Incorrect tactical path calculation

### ISSUE THREAD

**Issue by Agatae1** [ja2-stracciatella/ja2-stracciatella#375]
[save.ZIP](https://github.com/ja2-stracciatella/ja2-stracciatella/files/465891/save.ZIP)
In the attatched save, if I try to move Johny 5 tiles north, the path is OK, takes 11 AP.
If I trye to move him 6 tiles north, the path is longer and takes 20 AP.

**Comment by selaux** [comment]
I can reproduce this, not sure what is happening there and not sure how to actually debug this yet...

**Comment by akdjka** [comment]
Another instance in another sector. Try moving Johny 1 tile north or north east. The path is funny. If you do the walk and want to go back - the return path is normal.
Tested in 383211b
[s.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2776475/s.zip)

**Comment by akdjka** [comment]
Yet another sector yet another instance.
If you try to move Igor 2 fields away: NE,N the game chooses the best path. But try 1 tile north from that and it chooses a way around.

[s.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2799950/s.zip)

**Comment by flaviojs** [comment]
I determining that it was using `FindBestPath` and found that there is code to debug it.
I can visually debug the path after defining `_DEBUG`, defining `PATHAI_VISIBLE_DEBUG`, setting `gfDrawPathPoints` to `TRUE`, and adding missing includes.

5 tiles north takes 11 AP:
![5_cells_north](https://user-images.githubusercontent.com/1009600/62953949-62d89680-bde6-11e9-96ce-0cf68d334944.png)

6 tiles north takes 20 AP:
![6_cells_north](https://user-images.githubusercontent.com/1009600/62954123-bcd95c00-bde6-11e9-97c0-29bc6bc1f499.png)

From the screenshots, it appears to stop on the first path it finds, not the best path.

**Comment by flaviojs** [comment]
I'm not sure which algorithm is being used here, maybe something like A*?
The cost estimate of the remaining path (heuristic) is defined here:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/298096f574ae53599783d59ff1523806a7a9607b/src/game/Tactical/PathAI.cc#L120-L126

It seems they tried to introduce a bias towards the longest direction but they forgot something important... from what I recall, algorithms rely on the estimate to never exceed the real cost.

If the estimate exceeds the real cost then you lose the guarantee that you're getting the least-cost path from start to goal.

They should have decreased the estimated cost in the direction they want to promote instead of increasing the estimated cost in the direction they want to avoid.

**Comment by flaviojs** [comment]
Changing:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/298096f574ae53599783d59ff1523806a7a9607b/src/game/Tactical/PathAI.cc#L124
to:
```cpp
#define LOWESTCOST              EASYWATERCOST
#define ESTIMATEC               ( ( (dx<dy) ? (LOWESTCOST * (dx * 10 + dy * 6) / 10) : ( LOWESTCOST * (dy * 10 + dx * 6) / 10 ) ) )
```
confirms the estimate is indeed the problem, as can be seen here:
![5_cells_north_2](https://user-images.githubusercontent.com/1009600/62990581-6a2e8d00-be44-11e9-91e1-8b52ffb98220.png)
![6_cells_north_2](https://user-images.githubusercontent.com/1009600/62990582-6c90e700-be44-11e9-93c6-83fcbb99371d.png)

However, the reachable cells decrease. It's probably hitting the path-finding limits.
