### ISSUE TITLE
Out of bounds access in DecideAction.cc:1757:41

### ISSUE THREAD

**Issue by Agatae1** [ja2-stracciatella/ja2-stracciatella#378]
It can happen that BestThrow.bWeaponIn == NO_SLOT and NO_SLOT == -1.
I'm not sure, it may be that BestThrow.bWeaponIn is always -1 in this place.

**Comment by selaux** [comment]
Can you provide a save game or a decription of what to do to reproduce? Otherwise it's really hard to debug...

**Comment by flaviojs** [comment]
`CheckIfTossPossible` leaves `ubPossible` alone when there is nothing to throw and `usItem` will be `NO_SLOT`:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/c3e9284a195ef38d774ecb4b3c0cf601576cb996/src/game/TacticalAI/DecideAction.cc#L1710-L1713
which leads to a silent out of bounds access and an `usItem` value that I can't predict:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/c3e9284a195ef38d774ecb4b3c0cf601576cb996/src/game/TacticalAI/DecideAction.cc#L1752-L1758
This can lead to a call for spotters instead of normal AI behavior.
