### ISSUE TITLE
AIM mercs killed somewhere else erroneously ruin player's reputation

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#536]
Found on the GOG forums:
https://www.gog.com/forum/jagged_alliance_series/ja_2_mercs_refuse_to_renew_their_contractwith_his_friends_its_a_bug

@JAsmine-ja2: Can you please take a look at this issue?

thedkm posted May 01, 2017:
> In jagged Alliance 2 version 1.12, using Stracciatella, when there are too many dead and you offer a renew to one of your mercenary, he will refuse to renew his contract, but if one of his friend is in the team he will accept to stay, but there is a problem: for a while this method no longer works no matter how many deaths in my team the merc continues to refuse the renewal even if his friend is already in the team I play on stracciatella and I do not know if it is a bug or not. 
>  I remember that before that worked with Grizzly and Shadow for example, someone has the same problem as me? Or did I do something wrong? I remember perfectly that these quotes were triggered but since I launch the game under Stracciatella, impossible to trigger it. Even under the basic game of the Gog version without mod, these quotes never appeared. 
>  Maybe there is a reputation system like in Jagged Alliance 1, to know if the mercenaries will accept my offer or not, at least if such a system exists in J.A. 2 I never found it.

**Comment by Tercus** [comment]
I think it is related to a problem I am having at the moment: I cannot hire new ones from AIM, before they have been "warned" or because they expect more from their commander. None of my team died at all, so this is surprising.

But maybe something else caused this reaction. Two soldiers at AIM were killed while they were elsewhere on assignment. Savegame is attached:
[SaveGame05.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1050686/SaveGame05.zip)

**Comment by JAsmine-ja2** [comment]
Can confirm the bug in Tercus' savegame on both Stracciatella and Vanilla.

Basically it's like this: If too many mercs are killed in your campaign, new mercs won't join you.

Several things come into play though: Experienced mercs are more likely to refuse (e.g. in Tercus' savegame you can make Steroid join while Ivan will refuse) and the buddy-system plays a role as well.

But, in Tercus savegame things are definitely not right, because some mercs will refuse to join, although no one was killed in Arulco.
The game erroneously takes into account that two mercs were killed in another campaign.

**Comment by chmallon** [comment]
> The game erroneously takes into account that two mercs were killed in another campaign.

I don't think so.
gStrategicStatus.ubMercDeaths is the variable, which counts how many mercs were killed in Arulco.
It is only incremented in StrategicHandlePlayerTeamMercDeath().
To call this function, you need a SOLDIERTYPE as parameter.
Only hired mercs have such an object.
So this function cannot be called for a merc which is on another campaign.

Something else is going wrong here.
It might be interesting, what the value of the counter is.

**Comment by ShishkinP** [comment]
> if one of his friend is in the team he will accept to stay, but there is a problem: for a while this method no longer works no matter how many deaths in my team the merc continues to refuse the renewal even if his friend is already in the team

Fixed by #2059.

The Tercus' bug is unrelated. I'll take a look at it later.
