### ISSUE TITLE
Maximum militia Message at the wrong position

### ISSUE THREAD

**Issue by Tercus** [ja2-stracciatella/ja2-stracciatella#540]
This is probably also related to higher resolution but this just happened:
![screenshot_20170606_031217](https://cloud.githubusercontent.com/assets/3085791/26809639/97b5e092-4a66-11e7-8b07-cc4e32dd47a2.png)

The savegame is [here](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1053547/QuickSave.zip). Just let the time continue until 6:00 AM and you get that error. What happens is that two teams finish their task of training militia, but one team cannot continue (max militia).

**Comment by derSteFfi** [comment]
This is by design. When using the 'normal' generalizeds, central message Box for this, it looks like this:

![screen](https://user-images.githubusercontent.com/9593455/26865169-d3417aea-4b5b-11e7-8f4c-b993abbd3159.png)

This overlaps a few sectors, esspecially the one the message is about. Thats why in src/Game/Strategic/Town_Militia.cc:461:
```C
static void DoContinueMilitiaTrainingMessageBox(INT16 const sSectorX, INT16 const sSectorY, wchar_t const* const str, MessageBoxFlags const usFlags, MSGBOX_CALLBACK const ReturnCallback)
{
	if( sSectorX <= 10 && sSectorY >= 6 && sSectorY <= 11 )
	{
		DoLowerScreenIndependantMessageBox( str, usFlags, ReturnCallback );
	}
	else
	{
		DoScreenIndependantMessageBox( str, usFlags, ReturnCallback );
	}
}
```
While it may not be important for 'cant train anymore', the question whether to continue training should not overlap the sector itself, so the player can see the already trained militia. The placement of the box is not optimal, though. This is one of the things I would like to craft a resolution-inbdependant solution. So where should this box be placed? Or should the sector simply be overlapped?

**Comment by Tercus** [comment]
Does this also happen with the message of enemies attacking a town sector?
I think it would be fine to overlap the sector with the message. The sector is automatically selected after the message, and the view is also changed to show militia, so you know *where* the max-militia is reached.

**Comment by JAsmine-ja2** [comment]
@derSteFfi 
in a perfect world, the box (and any other pop ups) could be dragged around. But I guess this might be extremely hard to implent.
If the box has to be static in it's position, then I would suggest that the box just pops up in a centralized position, because _symmetry_ ;)
