### ISSUE TITLE
Investigate why LoadAmbientControlFile() is not called during save game loading

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#603]
This seems to be the underlying problem that caused issue #528.

>The crash is related to ambient sounds. Apparently LoadAmbientControlFile() is never called and therefore gAmbData is not initialized which in turn makes SetupNewAmbientSound() make a chain of calls that end with SoundLoadDisk() being called with an empty string ("") as argument.

**Comment by lynxlynxlynx** [comment]
I hit the crash again and came to the same conclusion. HandleNewSectorAmbience (LoadAmbientControlFile parent) only gets called when changing options or from PrepareLoadedSector. If you follow the latter higher, it leads us to SetCurrentWorldSector when loading a save (other callers exist). It gets called only when SaveGameHeader.fWorldLoaded is nonzero. Which is fine in my case, as gWorldSectorX and co are all zero, so it wouldn't have much of an effect. The first crash was while normally ingame, so it has nothing to do with loading one.

The other possibility is that the event didn't get cleared when it should have. In my case it was a RANGED_EVENT. However since it's on a timer, I see nothing wrong with that, unless it should have gotten preempted somewhere. 

Something just invalidated the current sector, which is fine, at least partially. It might be unlikely that there's not always a loaded sector (except for the beginning of the game and maybe if everyone dies in the current one), but is it wrong?

**Comment by momoko-h** [comment]
I believe the answer to the question in the title is: no good reason, it was simply an oversight. I added the necessary call in #1560, there doesn't seem to be anything left to do here.
