### ISSUE TITLE
arrows in IMP attribute allocation screen not exact

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#683]
because it came up in #644

![screen001](https://user-images.githubusercontent.com/17213795/34686414-bbe8d72c-f4ab-11e7-87ca-e963b0bae0a4.jpg)

The right arrow "more points" has a small area to the left, where it is not clickable (red area).
The left arrow "less points" has a small area to the right, where it is still clickable, although the graphic for the arrow ends earlier (green area).
We're talking about just a few pixels on each side, but it is noticeable (and annoying ;)

**Comment by lynxlynxlynx** [comment]
Did vanilla suffer the same?

**Comment by Manuel-K** [comment]
I've edited the start post to inline the image.

**Comment by JAsmine-ja2** [comment]
Yes, I just checked it. You can click slightly (handful of pixels) to the right of the "fewer points" arrow and still click it.

**Comment by Manuel-K** [comment]
It seems to be a bug in `QuickCreateButton`.

**Comment by JRF-github** [comment]
What a freaking annoying bug. After wasting hours combing through the button and mouse systems it turns out the problem here is completely trivial: the hand cursor's hot spot is not where you would think it is (at the top of the index finger) but rather at the top left corner of the image.

A far easier way to see this bug in action is the AIM home page. Move the cursor over the Members "button" and notice where it changes from a pointer to a hand and back again. Since this isn't really a button but a mouse region it's obvious the problem is not with the button system.
