### ISSUE TITLE
Improving project communication

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#702]
Following up from #495.

One of my takeaways is that a bugtracker-only community is not longterm viable. Nobody wants to use the existing forum or traditional stuff like irc and its successors. Github added some sort of discussion feature recently, but it's again more like a forum. I don't think that's enough, it needs to be more live, less dry for things not to pile up.

Initially, when we restarted the project, we had a skype call to see where we are and set expectations. Unless all you Germans are conspiring behind my back, that was the last real interaction. ;)

Is the fact that we're not on irc/slack/discord/whatever just due to inertia? And/or should we have scheduled meetings now and then?

Any other thoughts and ideas?

**Comment by selaux** [comment]
Hi @all,

sorry for not responding for some time, but I had to invest my time differently during the beginning of the year. That actually happened before #495, so I basically just skimmed it at the time and thought it was a long technical discussion what happened there. It's sad that we lost @Manuel-K as a contributor, even more so because we only have very few left.

I'm always pro experiments, so an IRC channel sounds good to me as a more direct way of communication, e.g. for short questions, bug reports, discussions. Though I am not sure if that would have avoided the above discussion though. I think that would be the job of a code of conduct. Not sure if it makes sense for a project of this size though.

For this instance I agree with @lynxlynxlynx, that the better communication imho would have been that "this is suboptimal" coupled with a concrete solution. Comments like "this is wrong" without any concrete suggestions cause frustration in people, especially when you are in an open source context where people invest their spare time. In our case this might even be worse as the "good" solution can be super hard to find in this haystack that we call our code, so we have to be aware of that. And there is one more thing that I want to add: if people think something is wrong, nothing keeps them from submitting another PR with a better solution, which will at the same time make them realize how much work the original author has put into his/hers.

**Comment by derSteFfi** [comment]
Hey,

my time on the project declined too, because of two reasons. First, and most important, I simply have less free time. And second, the two times I did show up during the last months seem to have had their impact on Manuels decision to leave. I'm still reflecting on that.

That being said, I'm glad to see we're thinking about solutions. For the kind of communication we want to achieve, I honestly do not care much. I can happily live with everyones 'tone' I could observe so far, and I can live with someone seeing problems there, too. If my tone strikes someone as unfriendly in a destructive manner, feel free to point it out.
For the technical way we communicate I agree this Issue tracker is not optimal. But considering our limited time, I also do not see a better alternative right now. IRC would require presence in the channel (sure, one can idle, but you need to have a client running...), slack looks kind of promising but I never used it before. Considering scheduled meetings, like the one we had when we started, it seems to me we would have a timing problem, but we can try of course.
The necessity of a 'meeting', in what form it may be, is given in my opinion. Progress got stuck a little, partly because we are not clear about mid- and longterm goals each of us has for the codebase. We should talk that out and see what the next items on the todo list are besides the usual housekeeping in this mess we call our codebase :)

I did consider not spending time on this project during the last weeks (mostly because my time is limited anyway) but I do not like the idea. I always had and still have fun tackling this project with you guys. And I still like the ideas we had, the android port, smoothless scrolling, open resources (maybe even scalable!), ...
I'm loking forward to whatever comes next :)

**Comment by lynxlynxlynx** [comment]
Thanks for chiming in. If we move to concrete steps, slack and discord have the upper hand on irc in terms of active persistence and files, discord also supports calls, but that's about it. IRC makes it easier for existing floss contributors to join, since many still use it and there are no registration steps.

I use all three, so no real preference.

My time for the project is going to get more limited in spring, but other than that, I don't expect much change.

**Comment by selaux** [comment]
So I got at least a little more time now and created the #ja2-stracciatella channel on [Freenode](https://freenode.net/), if somebody wants to hang out :wink:

**Comment by akdjka** [comment]
What's wrong with forums?

**Comment by lynxlynxlynx** [comment]
Like I said in the intro, we have one and it's unused. I post announcements there and sometimes someone asks something, but it's clearly not a developer favourite.
http://thepit.ja-galaxy-forum.com/index.php?t=thread&frm_id=224&

**Comment by lynxlynxlynx** [comment]
The ja2 1.13 team is using discord and offered us a separate channel if we ever wanted to take up the offer. They also started with irc and the move worked better for them. But, of course, it's our call and if we don't plan to chat, there's no difference.

**Comment by ja2-derek** [comment]
If you say the whole Bears' Pit is there, we really should try Discord. 

I am interested to getting started on dev work, and help to push for the next release, if I can.

**Comment by lynxlynxlynx** [comment]
It's just a thing of interest, we have plenty of places and tech that can facilitate chatting. So far though, not much buy-in.

**Comment by lynxlynxlynx** [comment]
Seems like we took a liking to discord (and deprecated IRC), so I don't think there's a need to keep this open.
