### ISSUE TITLE
Game.json in user directory (possibly ~/.ja2)

### ISSUE THREAD

**Issue by moll** [ja2-stracciatella/ja2-stracciatella#707]
Hey!

Thanks for the great JA2 icecream! Looking forward to getting back in the game. I'd like to tweak some settings in game.json, but when installed through a Linux distro package manager (Arch Linux through https://aur.archlinux.org/packages/ja2-stracciatella-git/, for example) game.json is located in /usr/share and isn't user-editable and is shared by everyone on the machine. Have you considered supporting game.json from ~/.ja2? That'd fit nicely with other user settings.

Thanks!

**Comment by lynxlynxlynx** [comment]
We have, yes, as the plan is to have the launcher mention the file #607.

**Comment by lynxlynxlynx** [comment]
Quoting myself from a closed PR:
> I don't like the (default) paths personally, since EXTRA_DATA_DIR will be undefined for most, so we'll default to the binary location. Which is not handy for installed or built-only versions: first has permission implications, while both suffer from losing the settings on a reinstall/rebuild.
> 
> So, I think we should first check if the file is in the home settings dir, alongside the saves and ja2.json.

#833 introduces a nice get_game_json_path where the change can be made.

**Comment by flaviojs** [comment]
It's fine to load a game.json from a yet-to-specified location in the home dir but that means there will be 2 game.json (EXTRA_DATA_DIR points to where the original is installed).
But first we need to define what happens to the original.
Is the original game.json ignored? Is it loaded as default values? Maybe both are possible and it depends on something inside the json file?

What about the other json files? They live next to game.json so maybe they should be treated the same?

What about mods? The mods directory is installed next to the externalized directory (where game.json lives) so maybe they should be treated the same?

The acceptable home dir path for game.json depends on the answers to the questions above.

PS- as a final note, I think the name EXTRA_DATA_DIR is confusing given the current usage (tell the code where the externalized/mods asset dirs are installed to), maybe it should be renamed to ASSETS_DIR

**Comment by lynxlynxlynx** [comment]
It's stored in stracciatella_home, nothing yet-to-be-specified. We could treat them as overrides, but all the values have defaults anyway, so I don't see a benefit in loading more than one file.

Externalized/ is for power users, so I wouldn't worry about that right now.

Mods are static, so any changes will be rare there.

**Comment by flaviojs** [comment]
If all values have defaults when they are not in the json, then it's fine to just shadow the original.

`game.json` could be in `~/.ja2/game.json` or `~/.ja2/externalized/game.json`. It's currently in `externalized/` and there is no GUI to edit it, does this mean it's for power users too? (I didn't even know you had it until I started messing with the code xD)

Rereading the issue, the main reasons for `game.json` in the home dir are that ` /usr/share`:
 * isn't user-editable
 * is shared by everyone on the machine

Which means that if 1 user starts messing with the json files or the mods, all the users will be affected.
The same applies to "Program Files" in windows.

Since shadowing the originals seems to be enough, I propose doing that.

**Comment by lynxlynxlynx** [comment]
game.json is nicely commented and meant to be edited by users. Very hard to shoot yourself in the foot there. Stuff under externalized? Not so much; we even include a disclaimer in the readme that some of the files shouldn't be touched. It's true that both are mentioned on the website though.

**Comment by flaviojs** [comment]
While playing around with rust (test-rustifying FileMan) I found that a shadowing strategy is already being used, and that the externalized dir is already used as a data dir. (`sti/interface/loadscreentab.sti`)

This is the shadowing hierarchy:

 * `(assets)/mods/(mod_name)/data` - caseless contents, only when using mods
 * `(assets)/externalized` - caseless contents
 * `(current_dir)` - case-sensitive contents, it's actually `(stracciatella_home)/tmp`
 * `(game_dir)/(caseless_data)` - caseless contents

Current `game.json` is always in `(assets)/externalized/game.json`.
`(stracciatella_home)' is `(home)/.ja2` on linux and `(home)/ja2` on windows.
caseless is a shorter word for case-insensitive.

-----

If it was up to me I would maybe make  `(current_dir)` top priority and allow `(stracciatella_home)` to shadow everything else, that way `game.json` can be loaded from there.
Currently only mods can shadow it.

For me anything other than using the launcher or the ja2 executable is potentially shooting yourself in the foot, so I wouldn't treat `game.json` differently from the other json files.

**Comment by flaviojs** [comment]
However, if we want to allow custom mods in the future, even when the user can't edit the assets dir, then it's better to treat `(stracciatella_home)` like an extra `(assets)` dir.
(same treatment for `mods` and `externalized`)

**Comment by flaviojs** [comment]
#290 mentions using `(assets)/externalized/data` as a data source.

Currently `(assets)/externalized` is being used as a data source  (`sti/interface/loadscreentab.sti`).
It is not obvious because there is no dir named data.
Maybe rename externalized to data to make it clear?

My proposal is to allow the mods/externalized dirs in `(stracciatella_home)` (`~/.ja2` in linux).
I think this ordering is good:
 * `(current_dir)` - tmp dir, writable
 * `(stracciatella_home)/mods/mod1/data`
 * `(assets)/mods/mod1/data`
 * `(stracciatella_home)/mods/mod2/data` - when we support multiple mods at the same time
 * `(assets)/mods/mod2/data`
 * `(stracciatella_home)/externalized`
 * `(assets)/externalized`
 * `(game_dir)/data`

@selaux your thoughts?

**Comment by lynxlynxlynx** [comment]
externalized is named externalized, since that's what it is — stuff that was unhardcoded from the original dump. Makes sense, so I'm against renaming. In other paths the name is not important though, we just need good instructions.

**Comment by selaux** [comment]
What about introducing `{assets}/data`, so we dont have confusion between `externalized` and `data`. And not using `exernalized` at all for data loading... (and with data I mean textures, sounds and such...

**Comment by flaviojs** [comment]
It may have come from the code but I still think it's data.
Mode specifically, data that was never "externalized" to the data dir in the original game, probably because it didn't change much over time.

In vanilla data:
 * `*.npc` files can be seen as a limited form of scripting
 * `*.bad` is a list of ambient sounds, when to play them and other parameters
 * `*.edt` is raw string data
 * there are binary files that could easily have been data in the code before, if ja2 was more focused on modding then item data would certainly be here

In externalized:
 * there are resource packs
 * there is a custom STI
 * `music.json` is a list of sounds and when to play them
 * there are jsons with string data
 * there is item data, inventory data and `game.json`

In my eyes, maybe only `game.json` and resource packs are not data.

**Comment by lynxlynxlynx** [comment]
I don't think anyone would disagree on the last point. Unhardocoded is short for unhardcoded data and sometimes rules, but in ja2s that's all in game.json.

**Comment by cyagit** [comment]
> We have, yes, as the plan is to have the launcher mention the file #607.

Hello.

The launcher now displays the path for game.json.

I too would like to move the folder /usr/share/ja2 to a different location. It seems this cannot be set in the launcher as of now. Would there be another way to let's say start the launcher and pointing the path for the ja2 folder to /home/play/.ja2/?

Thanks for your work!

**Comment by ja2-derek** [comment]
This does not seem to work yet. I tried with the nightly `.deb`

Current situation:
 - "JA2 Home Dir" - `~/.ja2`:  is the configFolder, which is only launcher config (ja2.json) and saves. Not used for mods or data.
 - "Extra data directory" `/usr/share/ja2`: this is the assets shipped with stracc. Not editable to non-root users.
 - "Data directory" - this specified by the user, and so probably the user has write permissions. But it has lower priority in the VFS_ORDER. `game.json` is actually supported here, but it will always get overriden by `/usr/share/ja2`

So there are no valid ways to edit JSON data or install new mods without root permissions.

How about:
- Add a VFS layer `~/.ja2/data` with high VFS_ORDER, so user override data file; and
- Add support for `~/.ja2/mods/`, so user can install new mods here (may require launcher changes too)

**Comment by ja2-derek** [comment]
It's there in the latest Nightly (ja2-stracciatella_0.17.0-20200628+1aaac70_amd64.deb). To customize your game policy:

1. `mkdir -p ~/.ja2/data`
2. `cp /usr/share/ja2/externalized/game.json ~/.ja2/data/`
3. Edit game.json to your liking, and start the game
