### ISSUE TITLE
Attacking: Different result in Stracciatella vs. Vanilla

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#777]
### Attacking leads to a different outcome, depending on game version: Stracciatella vs. Vanilla
Load this savegame (from  #189) in JA2S and attack the enemy with Johny. Johny will hit the enemie's torso, regardless of the aiming level.
Load the same savegame in Vanilla (I tried 1.12 Gold) and perform the same attack. Johny will MISS the enemy.
This should not happen.
[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2798958/QuickSave.zip)

**Comment by JAsmine-ja2** [comment]
We have a similar situation here: #755
(one seed leading to different results in JA2S vs Vanilla)

**Comment by chmallon** [comment]
The (pseudo-)random number generator works differently than in vanilla.
(actually two: Random() and PreRandom())
Originally it did '$RANDOM * range / RAND_MAX % range'.
(this also has several problems, which are not relevant here)
On Windows RAND_MAX is 32767, so this (somewhat) works.
On platforms with larger RAND_MAX, typically about 2**31, this breaks when doing the calculation in 32 bit.
So due to the altered calculation, you get different results.

For PreRandom() this could be restored to vanilla behavior, because this cycles over the same 256 numbers over and over anyway.
(See vanilla commented out comment in PreRandom().)
The values in guiPreRandomNums[] could be reduced to 32767 and the calculation restored -- while replacing RAND_MAX by 32767.
This should restore consistent behavior for PreRandom() with vanilla.

Consistent behavior for Random() is not even given for vanilla, because it uses a time-based seed.

**Comment by flaviojs** [comment]
This is just my opinion.
For me having a non-uniform random distribution is a bug and it's great that it has been fixed.
Therefore different results from vanilla are expected and this is not a bug and neither is.

On the flipside.
It is understandable that some players would want the exact same result as vanilla, so for them this is considered a bug.

A `game.json` option could be added to get the original behavior, but I think that is something that will eventually break.
All it takes is a single bugfix that leads to calling one more or one less `PreRandom` to start getting different results.
An example of such a fix is #812, which doesn't affect combat because there are no crows during combat.
