### ISSUE TITLE
Some sounds sound wrong.

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#78]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

----------------------------------------

After having played v0.12.189 for some time, I realized, that some sounds sound different than they used to in vanilla JA2 or v1.13.
Prominent examples are: "walking on dirt" and "opening laptop".

This is an issue I already discussed with BirdFlu, almost 2 years ago when he was working on SMP (which was based on Stracciatella).

The discussion thread on BP forums can be found here: [http://www.ja-galaxy-forum.com/board/ubbthreads.php/topics/291952/1.html](http://www.ja-galaxy-forum.com/board/ubbthreads.php/topics/291952/1.html)

I don't expect anyone to read the whole thing. Here's my initial report:

*"1) The sound when opening/closing the laptop sounds wrong somehow. Much brighter and "cheaper" then I'm used to.
2) The same is true for other sounds: starting of players turn (interrupt), target out of range, walking on dirt (roads), opening doors."*

After some discussion, BirdFlu wrote: 

*"I stopped the time for Hitman walking from one side to the otherside of the MAP (a9):
- 56 seconds for Ja2 Gold
- 47 seconds for Ja2 Stracciatella*

*Either this speed difference is the cause for 1) or it is the SDL library. Since this effect also occurs on Stracciatella, I'm quite sure that it is nothing that i could have introduced."*

Imo, this is a severe issue!

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/78

**Comment by lynxlynxlynx** [comment]
There are two things there, so ideally it would be split into separate entries:
- different sound (needs a sound person to hear-reverse-engineer the difference)
- general speed or walking speed mismatch

**Comment by JAsmine-ja2** [comment]
I'm a sound person. I present to you the difference in "opening laptop"-sound in Vanilla JA2 vs. JA2 Stracciatella.

I recorded the sounds for opening and closing the laptop. Recording was done not via line-in but directly from the speakers, so that the clicking of the mouse is recorded, too.

First example is the "opening laptop" sound taken from vanilla JA2 v1.12, English version. Notice how the sounds roughly starts at 1,25 secs and ends at 2,2 secs. The sound takes roughly 0,95 secs.

![vanilla](https://cloud.githubusercontent.com/assets/17213795/13202132/511282fc-d88f-11e5-91e7-912176851bf7.jpg)

The second example comes from JA2 Stracciatella v0.12.352. Stracciatella uses the exact same installation of JA2 v1.12 as in the first example! Notice how the sound roughly starts at 1,15 secs and ends at 1,65 secs. The sound is about 0,5 secs in length.

![stracciatella](https://cloud.githubusercontent.com/assets/17213795/13202131/510c8f14-d88f-11e5-8610-f1899f868c42.jpg)

As you can see, the same sound in the same situation from the same installation of JA2 is only about 50% in length in Stracciatella.

You can also easily hear it in the attached files. What you can hear there is:

- mouse click
- opening laptop
- closing laptop

and that two times each in Vanilla JA2 and Stracciatella. No need to be some kind of audio technician here, as the difference is very obvious.

[laptop-sounds.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/139562/laptop-sounds.zip)

As I wrote before, this extreme difference does not apply to all sounds. For example, speech sounds perfectly fine in Stracciatella. The music is fine, as well.
Another example for a sound that is also "too fast" is walking/footsteps.

**Comment by lynxlynxlynx** [comment]
What a stellar investigation! :+1: 

I guess this also means the volume range is different?

It's quite possible it's the same timing thing. Does setting ms_per_game_cycle in game.json to 50 (double, since the sound is roughly half as long) make things better?

**Comment by JAsmine-ja2** [comment]
Changing ms_per_game_cycle in game.json to 50 doesn't seem to have an impact on the sound.

Another interesting observation: The animation for "zooming into the laptop" seems to take the same time in vanilla and Stracciatella. It's only the sound which is too fast in Stracciatella.

**Comment by selaux** [comment]
Here is the WAV used by the game. Seems like the vanilla version is correct and we play the sound in a distorted way.

[LAPTOP POWER UP (8-11).WAV.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/139852/LAPTOP.POWER.UP.8-11.WAV.zip)

**Comment by selaux** [comment]
Could it be that the encoding of the files is different? Laptop opening / closing as well as endturn use `11025` bits per second to encode while most others use `22050bps`. Some use `44100bps` but they are downsampled on load to `22050bps`, so we might have to upsample the `11025bps` ones (not tested though)

**Comment by selaux** [comment]
@JAsmine-ja2 Can you whether #232 fixes this issue? The sound might be minimally distorted, but the same goes for other `44100Hz` sounds.

**Comment by selaux** [comment]
@JAsmine-ja2 As discussed in the meeting, I built a windows version of the fix branch so you can test it without needing to build the package yourself.
[ja2-v0.14.xx-win.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/159203/ja2-v0.14.xx-win.zip)

**Comment by JAsmine-ja2** [comment]
Thx. This seems to fix the issue. At least, it sounds quite the same now compared to vanilla JA2. I don't have access to my recording tools atm. I will be able to analyze it thoroughly next week.
(sorry I couldn't attend the meeting)

**Comment by lynxlynxlynx** [comment]
If it sounds the same, I don't think you have to bother with a spectrum analysis. If you still want to do it, go ahead. If you find something terrible is wrong, please reopen the bug.
