### ISSUE TITLE
Hotkey requests

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#82]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

(I have edited an existing issue to make things more clear...)

I really miss a hotkey for climbing/jumping. There was none in vanilla JA2. In v1.13, the [j] key is used for it.
The annoying thing is, that I usually have the "team view" in tactical view. But in order to jump, I need to change to "inventory view" and press the ladder icon. Tedious.

If you consider adding this hotkey, I would highly recommend you to also add it to the help screen. 1.13 is full of poorly documented (or undocumented) features...

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/82

**Comment by JAsmine-ja2** [comment]
When scrolling the mercs on the A.I.M. site, it would be helpful to be able to do so with the cursor keys. The space oder return key could be used to make a call.

Also, a hotkey for closing websites would be handy, too.
Since ESC is used to close the laptop, maybe BACKSPACE could be used to close websites and return to the desktop?
