### ISSUE TITLE
Artifacts when entering a map

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#95]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

Sometimes, when entering a map via "merc placement" (before a battle), there are "artifacts" present on the map. Mostly lights (maybe from break lights), sometimes patches of gas (tear/smoke). Here is an example:
![http://img.xrmb2.net/images/439356.jpeg](http://img.xrmb2.net/images/439356.jpeg)

Note, that I've not entered the sector before in this campaign. Also, I'm entering from the north and the light is somewhere in the south. When I save the game (after merc placement) and then quit and load again, the light is gone.

This has happened at least 3 times in my running campaign. I have not yet made out a pattern behind this...

Forgot to mention: It's v0.12.189 with 800x600 resolution.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/95

**Comment by derSteFfi** [comment]
maybe a duplicate of #180 ?

**Comment by lynxlynxlynx** [comment]
Yes, just the other way around, since this one is older and also mentions grenades.

> Perhaps they were break lights used during ai vs ai battles (bloodcats), but didn't properly expire.

**Comment by JAsmine-ja2** [comment]
![light](https://cloud.githubusercontent.com/assets/17213795/18971226/928bfd68-8694-11e6-887d-22c1ebb1575c.jpg)

Upon entering the sector, an illuminated area was shown on the placement screen.
I had a battle in this sector before, and threw a breaklight in the same position. But that was several days ago.
So, the breaklight is somehow still visible when placing mercs. In tactical view, it is invisible. Hard to say, since it's daytime.

[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/501659/QuickSave.zip)

**Comment by JAsmine-ja2** [comment]
- In every full playtrough, I encounter this issue several times (maybe ~10 times?).
- I've seen this issue in sectors that I'd visited before and in sectors that were entered for the first time.
- Unfortunally, I can't yet see the pattern, according to which the issue shows up. It seems random.

Questions/crappy theory:
Maybe, the game keeps track on where (gridno) a breaklight was lit and just stores this info (gridno) independent from the sector?
Maybe, when the player leaves a sector while there is an active breaklight around, the relevant info remains stored somewhere?
And when a new sector is entered, the info (lit breaklight at gridno x) gets applied to the new map under certain conditions?

Sorry, if all this is totally off track...

**Comment by lynxlynxlynx** [comment]
My main guess would be different: when leaving the sector, it is unloaded, so time doesn't pass anymore and things can't expire until it resumes. Midimap placement happens before that, so it doesn't get a chance to be updated from the new map yet.

**Comment by JAsmine-ja2** [comment]
This issue is rather annoying. 
It happens very often.
Here I have another instance whith two savegames, one before entering the sector and one after entering.
![lights](https://cloud.githubusercontent.com/assets/17213795/19032308/3f154136-8959-11e6-822b-bebb2015a7be.jpg)

[lights.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/505852/lights.zip)

**Comment by JAsmine-ja2** [comment]
Nothing has changed about this bug. I just ran into it several times in my current playtest. In fact, it happens very often.
I can't make out any pattern behind this behavior. It happens in sectors that the player already fought in before, but it also happens in sectors that are entered for the very first time. 

[SaveGame11.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1629233/SaveGame11.zip)


![screen001](https://user-images.githubusercontent.com/17213795/34914951-4c32a252-f91d-11e7-965b-f5409d322d2c.jpg)
